using System.Collections.Generic;

namespace DarkSoulsOBSOverlay.Models.Mappings
{
    public static partial class Mappings
    {
        public static readonly Dictionary<int, string> Places = new()
        {
            { 1000, "Depths" },
            { 1010, "Undead Burg" },
            { 1011, "Undead Parish" },
            { 1020, "Firelink Shrine" },
            { 1100, "Painted World of Ariamis" },
            { 1200, "Darkroot Garden" },
            { 1201, "Darkroot Basin" },
            { 1210, "Sanctuary Garden" },
            { 1211, "Oolacile Sanctuary" },
            { 1212, "Royal Wood" },
            { 1213, "Oolacile Township" },
            { 1214, "Chasm of the Abyss" },
            { 1215, "Battle of Stoicism" },
            { 1216, "Battle of Stoicism Gazebo" },
            { 1300, "The Catacombs" },
            { 1310, "Tomb of the Giants" },
            { 1320, "The Great Hollow" },
            { 1321, "Ash Lake" },
            { 1400, "Blighttown" },
            { 1401, "Queelag's Domain" },
            { 1410, "Demon Ruins" },
            { 1411, "Lost Izalith" },
            { 1500, "Sen's Fortress" },
            { 1510, "Anor Londo" },
            { 1600, "New Londo Ruins" },
            { 1601, "The Abyss" },
            { 1602, "Valley of Drakes" },
            { 1700, "The Duke's Archives" },
            { 1701, "Crystal Cave" },
            { 1800, "Kiln of the First Flame" },
            { 1801, "Firelink Altar" },
            { 1810, "Northern Undead Asylum" },
            { 2000, "Firelink Shrine" },
            { 2001, "Sunlight Altar" },
            { 2002, "Anor Londo" },
            { 2003, "Chamber of the Princess" },
            { 2004, "Darkmoon Tomb" },
            { 2005, "The Abyss" },
            { 2006, "Daughter of Chaos" },
            { 2007, "Altar of the Gravelord" },
            { 2008, "Stone Dragon" },
            { 2009, "Sanctuary Garden" },
            { 2010, "Oolacile Sanctuary" },
            { 2011, "Oolacile Township" },
            { 2012, "Chasm of the Abyss" },
            { 2013, "Oolacile Township Dungeon" },
            { 2014, "Depths" },
            { 2015, "Undead Parish" },
            { 2016, "Painted World of Ariamis" },
            { 2017, "Tomb of the Giants" },
            { 2018, "The Duke's Archives" },
            { 2019, "Crystal Cave" },
            { 2020, "Catacombs" },
        };
    }
}
